version: 2.1
jobs:
  make:
    docker:
      - image: pixey/ipxe-build

    parameters:
      binary_name:
        type: string

    steps:
      - checkout

      - run:
          name: Make binary
          command: "cd ./src && make << parameters.binary_name >>"

      - run:
          name: Dump files
          command: find .

      # - persist_to_workspace:
      #     root: src/
      #     paths:
      #       - "bin-*/**"

workflows:
  build_and_deploy:
    jobs:
      - make:
          binary_name: bin-x86_64-efi/ipxe.efi