version: 2.1
jobs:
  make:
    docker:
      - image: pixey/ipxe-build

    parameters:
      # iPXE Configuration can be defined as variables here

      artifact_name:
        type: string
      binary_name:
        type: string

    steps:
      - checkout

      - run:
          name: Make binary
          command: "cd ./src && make << parameters.binary_name >>"

      - store_artifacts:
          path: "./src/<< parameters.binary_name >>"
          destination: "<< parameters.artifact_name >>"

  github_release:
    docker:
      - image: circleci/golang:1.8

    steps:
      - attach_workspace:
          at: ./artifacts

      - run:
          name: "Publish Release on GitHub"

          #TODO: Replace hardcoded tag value
          command: |
            go get github.com/tcnksm/ghr
            VERSION=0.0.1-alpha
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  build_and_deploy:
    jobs:
      - make:
          binary_name: bin-x86_64-efi/ipxe.efi
          artifact_name: x86_64_ipxe.efi

  publish:
    jobs:
      - github_release