version: 2.1
jobs:
  make:
    docker:
      - image: pixey/ipxe-build

    parameters:
      # iPXE Configuration can be defined as variables here

      binary_name:
        type: string

    steps:
      - checkout

      - run:
          name: Make binary
          command: "cd ./src && make << parameters.binary_name >>"

      - persist_to_workspace:
          root: "./src/"
          paths:
            - "<< parameters.binary_name >>"

  github_release:
    docker:
      - image: circleci/golang:1.8

    steps:
      - attach_workspace:
          at: ./src/

      - run:
          name: Dump
          command: find .

      - run:
          name: "Publish Release on GitHub"

          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./src/

workflows:
  build_and_deploy:
    jobs:
      - make:
          binary_name: bin-x86_64-efi/ipxe.efi

      - make:
          binary_name: bin-x86_64-pcbios/undionly.kpxe

      - make:
          binary_name: bin-x86_64-pcbios/undionly.kkpxe
      
      - github_release:
          requires:
            - make
          filters: # Release only tags
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/