name: Build

on: push
env:
  arch: noarch
  org: hpe
  repo: csm-rpms
  stable: unstable
  target_os: sle-15sp3
jobs:

  x86:
    name: x86
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install packages
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update -q
          sudo apt install -y -qq -o Acquire::Retries=50 \
                           mtools syslinux isolinux \
                           libc6-dev-i386 libc6-dbg:i386 valgrind 
      - name: Build (BIOS)
        run: |
          make -j 4 -C src

      - name: Build (EFI)
        run: |
          make -j 4 -C src \
                bin-x86_64-efi/ipxe.efirom \
                bin-x86_64-linux/tests.linux
                CONFIG=metal EMBED=config/metal/metal.ipxe

      - name: Test
        run: |
          valgrind ./src/bin-x86_64-linux/tests.linux

  rpm:
    name: RPM Distribution
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install packages
        run: |
          sudo apt update -q
          sudo apt-get install -qq -y -o Acquire::Retries=50 \
               binutils gcc make liblzma-dev git-buildpackage-rpm

      - name: Build (RPM)
        run: |
          make rpm

      - id: get-name
        run: |
          repo_name=$(echo $GITHUB_REPOSITORY | cut -d/ -f2)
          echo "::set-output name=repo_name::$repo_name"

      - name: Publish RPM(s)
        uses: advancedcsg-open/action-jfrog-cli@master
        with:
          url: ${{ secrets.ARTIFACTORY_URL }}
          credentials type: 'accesstoken'
          user: ${{ secrets.ARTIFACTORY_ALGOL60_USERNAME }}
          access token: ${{ secrets.ARTIFACTORY_ALGOL60_TOKEN }}
          args: u "dist/rpmbuild/RPMS/${{ env.arch }}/" "/${{ env.repo }}/${{ env.org }}/${{ env.stable }}/${{ env.target_os }}/${{steps.get-name.outputs.repo_name}}/${{ env.arch }}/" --recursive=true

      - name: Publish SRPM(s)
        uses: advancedcsg-open/action-jfrog-cli@master
        with:
          url: ${{ secrets.ARTIFACTORY_URL }}
          credentials type: 'accesstoken'
          user: ${{ secrets.ARTIFACTORY_ALGOL60_USERNAME }}
          access token: ${{ secrets.ARTIFACTORY_ALGOL60_TOKEN }}
          args: u "dist/rpmbuild/SRPMS/" "/${{ env.repo }}/${{ env.org }}/${{ env.stable }}/${{ env.target_os }}/${{steps.get-name.outputs.repo_name}}/src/" --recursive=true
